### PR TITLE
WIP: Add journalbeat

### PR DESCRIPTION
**Pull request by vquiering**
This PR adds the journalbeat. It will be downloaded from the official releases (https://github.com/mheese/journalbeat/releases) and configured just like the other beats shipper.

### CODE REVIEW

**Comment by psmiraglia** [comment]
Hi @vquiering. First of all, sorry for my late reply.

You're requesting to include a beat that, according to my knowledge, is not available within the official Elastic repository. So, we can define `journalbeat` as community beat.

I think community beats could be managed as follows:

* beat specific files under `beats/community/<beat>` (e.g. `beats/community/journalbeat`)
* a pillar key to enable/disable community beats (e.g. `beats:enable_community`)
* beat specific pillar keys under `beats:community:<beat>` (e.g. `beats:community:journalbeat`)

```yaml
beats:
  include_community: True
  ...
  community:
    journalbeat:
      ...
```
What do you think about that?

**Comment by vquiering** [comment]
Hi @psmiraglia,
sounds good to me, except for the pillar key to enable community beats.
Since you call the state by `beats.community.<beat>` and you define the pillar under `beats:community:<beat>` I don't think it is necessary to define the extra key.

I will implement the changes next week.

**Comment by vquiering** [comment]
Hi @psmiraglia,
I just moved the journalbeat to a community subdir with all the necessary changes. Did not test this yet. This is why I renamed the PR to WIP.
I will test it next week.

**Comment by psmiraglia** [comment]
Ok

**Comment by vquiering** [comment]
@psmiraglia 
Did use a wrong source branch in this pr. Opened a new one which is fully tested.

**Pull request closed without merging**
